### ISSUE TITLE
[Design Doc] 言語対応によるデグレ

### ISSUE THREAD

**Issue by nozomi-koborinai** [Mood-Trend/mood-trend-flutter#56]
## Title

Mood Trend

- 言語対応によるデグレ

## Overview

異なる文言が出ている箇所がいくつかある
一旦見つけたものを挙げている
他にも無いか確認すること
<img width="363" alt="image" src="https://github.com/Mood-Trend/mood-trend-flutter/assets/39579511/1e274416-2af4-44c7-b3c1-09517f806334">
<img width="374" alt="image" src="https://github.com/Mood-Trend/mood-trend-flutter/assets/39579511/6c930d46-885c-438e-b83b-4e3f5c9fd2ba">
<img width="374" alt="image" src="https://github.com/Mood-Trend/mood-trend-flutter/assets/39579511/d7b85b8c-fbfd-434b-a65e-43c737dc6c44">

## Context

異なる文言が出ている箇所がいくつかあるため

## Goals

対象タスクで **やること**

## Non Goals

対象タスクで **やらないこと**

## Architecture

アプリケーションの全体像、Flutter での全体像に関する説明

必要であれば記載する

## Alternative Solutions

代替の解決策やアーキテクチャがある場合、ここに記載

合わせて、その案を選ばなかった理由も記載

### Risks

この変更によってどのようなリスクが導入される可能性があるか

## References

参考資料などのリンク

**Comment by nozomi-koborinai** [comment]
@Satoru0529 
日本語だけでなく、他の言語も間違いなさそうか確認いただけると助かります 🙏
誤字のところは、変数の指定間違い or そもそも変数の中の文字列が間違っているというパターンがあり得るのでそこを注意していただけると幸いです。
わからなければいつでもメンションください！！

**Comment by Satoru0529** [comment]
@nozomi-koborinai 
先日お話ししてたシートは下記の画像のような感じになっていて、
日本語を元に他の言語を翻訳して、ワンクリックで全ての言語のARBファイルを出力できるようになってます！！

アプリに関してはまだ全ての画面を確認できていないため、来週までに確認しておきます！！

![image](https://github.com/Mood-Trend/mood-trend-flutter/assets/131788036/adc7b981-0a33-4dd7-82a7-4cba4e24550b)
