### ISSUE TITLE
[Design Doc] 調査① モーダルのプロトタイプ作成

### ISSUE THREAD

**Issue by nozomi-koborinai** [Mood-Trend/mood-trend-flutter#7]
## Title

Mood Trend

- 調査① モーダルのプロトタイプ作成

## Overview

- [Figma](https://www.figma.com/file/exTigNcmPKw7jZ1zOeI4cQ/%E6%B0%97%E5%88%86%E3%82%B0%E3%83%A9%E3%83%95?type=design&node-id=0-1&mode=design&t=hcalT9F4T5Hzj7gs-0) デザインのモーダルに定義されたデザインを作成する
  - `lib/presentation/research/research_1.dart` を使用すること
  - ブランチの運用方法に関しては [Notion](https://www.notion.so/Development-Lifecycle-ae740748e0614eebb89768172d36c2b6#ac025a69abca4d3c90aab7567d8d7d93) を参照して記載の内容に従うこと

## Context

- 基本デザイン実装のため

## Goals
対象タスクで **やること**

Overview 記載の通り

## Non Goals
対象タスクで **やらないこと**

Firebase (Firestore, Cloud Storage) 等の連携

## Architecture

必要であれば記載する

- 特になし

## Alternative Solutions

- 特になし

### Risks

- 特になし

## References

参考資料などのリンク

**Comment by nozomi-koborinai** [comment]
@IkemotoNanako 
もし書いていることが意味不明だったり、そもそも何やればいいんだろうという場合は、いつでも相談いただいて大丈夫です🙆‍♂️
（ちなみに、作業をせかしているわけではないのでご安心を🙌）

**Comment by IkemotoNanako** [comment]
@nozomi-koborinai 
モーダルの処理はかけたのですが、プルリクエストが出せず困っています
もしかしたら権限がないのかも？

**Comment by nozomi-koborinai** [comment]
@IkemotoNanako 
権限付与しました！これで再度試してみていただけますでしょうか？？

**Comment by IkemotoNanako** [comment]
@nozomi-koborinai 
コマンドでのプッシュはできましたが、sourcetreeでのプッシュはなぜかできませんでした。次のプルリクでもできなければ理由を探ろうと思います。
また、GitHubで作成したブランチが確認できず、プルリクエスト作成のための緑色のボタンもありませんでした。
また明日考えます。

**Comment by IkemotoNanako** [comment]
@nozomi-koborinai 
```
git add .
git commit -m "feat:モーダル作成"
git push origin main
```
の順でコマンドを実行し
`Everything up-to-date`
と出ましたが、github上に反映されません。
どうすれば良いか教えていただけませんか？
一度ブランチを削除し、もう一度作成して同じことを行うことは試しました。
sourcetree上では権限がないと出ています。
