### ISSUE TITLE
[Design Doc] Android の審査

### ISSUE THREAD

**Issue by nozomi-koborinai** [Mood-Trend/mood-trend-flutter#75]

**Comment by nozomi-koborinai** [comment]
審査待ち

**Comment by nozomi-koborinai** [comment]
2024/04/07
Android 開発者アカウント閉鎖のため、新しくアカウントを作成

**Comment by nozomi-koborinai** [comment]
2024/4/10
パッケージも変更する必要ありだったため、Android のみ `com.moodtrend.app` から `com.mood_trend.app` とした

**Comment by IkemotoNanako** [comment]
https://play.google.com/console/u/0/developers/4865307214481470875/app/4973912248395605808/tracks/production
2024/10/22　
審査中

**Comment by IkemotoNanako** [comment]
公開済みなので閉じます

https://play.google.com/store/apps/details?id=com.moodtrend.mood_trend_flutter
